services:
  db:
    container_name: notes_app
    image: postgres:18
    restart: always # Всегда перезапускается в случае каких либо неполадок
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
